(function() {var implementors = {};
implementors["libffi"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"libffi/middle/struct.Builder.html\" title=\"struct libffi::middle::Builder\">Builder</a>",];
implementors["libffi_sys"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"libffi_sys/struct._ffi_type.html\" title=\"struct libffi_sys::_ffi_type\">_ffi_type</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"libffi_sys/struct.ffi_cif.html\" title=\"struct libffi_sys::ffi_cif\">ffi_cif</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"union\" href=\"libffi_sys/union.ffi_raw.html\" title=\"union libffi_sys::ffi_raw\">ffi_raw</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"libffi_sys/struct.ffi_closure.html\" title=\"struct libffi_sys::ffi_closure\">ffi_closure</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"libffi_sys/struct.ffi_raw_closure.html\" title=\"struct libffi_sys::ffi_raw_closure\">ffi_raw_closure</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"libffi_sys/struct.ffi_java_raw_closure.html\" title=\"struct libffi_sys::ffi_java_raw_closure\">ffi_java_raw_closure</a>",];
implementors["mpi"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"mpi/request/struct.StaticScope.html\" title=\"struct mpi::request::StaticScope\">StaticScope</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
