#include "rsmpi.h"

const MPI_Datatype RSMPI_FLOAT = MPI_FLOAT;
const MPI_Datatype RSMPI_DOUBLE = MPI_DOUBLE;

const MPI_Datatype RSMPI_INT8_T = MPI_INT8_T;
const MPI_Datatype RSMPI_INT16_T = MPI_INT16_T;
const MPI_Datatype RSMPI_INT32_T = MPI_INT32_T;
const MPI_Datatype RSMPI_INT64_T = MPI_INT64_T;

const MPI_Datatype RSMPI_UINT8_T = MPI_UINT8_T;
const MPI_Datatype RSMPI_UINT16_T = MPI_UINT16_T;
const MPI_Datatype RSMPI_UINT32_T = MPI_UINT32_T;
const MPI_Datatype RSMPI_UINT64_T = MPI_UINT64_T;

const MPI_Datatype RSMPI_DATATYPE_NULL = MPI_DATATYPE_NULL;

const MPI_Comm RSMPI_COMM_WORLD = MPI_COMM_WORLD;
const MPI_Comm RSMPI_COMM_NULL = MPI_COMM_NULL;
const MPI_Comm RSMPI_COMM_SELF = MPI_COMM_SELF;

const MPI_Group RSMPI_GROUP_NULL = MPI_GROUP_NULL;
